# Generated by Django 5.1.6 on 2025-02-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_post', '0003_alter_imagepost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='title',
        ),
    ]
