# Generated by Django 5.1.6 on 2025-02-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_post', '0005_alter_imagepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
